#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
  path: /logout

perfilUsuario:
  path: /perfilUsuario
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: perfilUsuario.html.twig

cambiarAvatarFormulario:
  path: /cambiarAvatarFormulario
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: cambiarAvatar.html.twig

cambiarClaveFormulario:
  path: /cambiarClaveFormulario
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: cambiarClave.html.twig

conOlvidada:
  path: /conOlvidada
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: contraseñaOlvidada.html.twig